### PR TITLE
Add basic activity log

### PR DESCRIPTION
**Pull request by dcbr**
This PR adds a basic implementation for an activity log in each group. Currently 4 types of activity are logged: updating the group settings and creating/updating/deleting an expense. If an active user is configured, the activity message includes the name of that active user. If #95 is approved, the "infinite scroll" feature can also be applied to this activity log (the implementation here is derived from the expense list).

image

Related issues are #15, #103 and #106.

### CODE REVIEW

**Comment by ChristopherJohnston** [comment]
nice! Might also be good to have the activity history for an individual expense at the bottom of the edit expense page.

**Comment by justcallmelarry** [comment]
Could be nice if the expenses were links to the expense in question!

**Comment by dcbr** [comment]
@justcallmelarry They actually are linking to the expense, as long as it was not deleted in the meantime. This is denoted by the small arrows on the right (and a pointer cursor while hovering).

**Comment by justcallmelarry** [comment]
@dcbr ah ok! nice! was not clear from the screenshot for me 😅 i was looking for the name of the group to be a link or similar

**Comment by justcallmelarry** [comment]
This would also benefit from soft-deleting expenses, so that you can un-delete the expense from the log!

**Comment by dcbr** [comment]
@justcallmelarry Yes indeed! However, I didn't want to introduce too many changes here, and just introduce a basic version that can later be extended. But I agree soft-deletion would be a nice feature for a follow-up PR :)

**Comment by sh3hz** [comment]
Hi @scastiel, could you please review and merge this feature when you have a chance? This is definitely required for the app. Thanks!

**Comment by ChristopherJohnston** [comment]
@scastiel I think the app will benefit greatly from this PR

**Comment by shynst** [comment]
> Might also be good to have the activity history for an individual expense at the bottom of the edit expense page.
> 
Great idea!

**Comment by scastiel** [comment]
Thanks a lot @dcbr, amazing contribution!

**Pull request merged**
