### PR TITLE
fix Dockerfile

### PR DESCRIPTION
**Pull request by bitgroestl**
I unintentionally messed up the original pull request (#200) by deleting the my forked repo that contained the changes. That's why i'm now creating this new identical pull request. Sorry for the inconvenience, i'm still learning how Github works.

### CODE REVIEW

**Review by justcallmelarry — APPROVED** [review]

**Comment by TimZava** [comment]
Can this PR be merged? Would like to be able to build in main without manually grabbing these changes

**Comment by Empor-co** [comment]
yes, please a fix for that would be highly appreciated - it's broken now for 6+ weeks

**Review by totti-rdz — APPROVED** [review]

**Comment by Mubelotix** [comment]
@scastiel Can you please merge this? Reviewing shouldn't take more than 15 seconds

**Comment by Mubelotix** [comment]
Thank you ! :tada:

**Pull request merged**
