### PR TITLE
Implement "infinite scroll" for expenses

### PR DESCRIPTION
**Pull request by shynst**
## Motivation

As @scastiel mentioned in #30 the expense list gets quite slow when dealing with a large number of transactions. I have managed to import my "home expenses" group over from Splitwise which dates back to 2018 and features around 3000 expenses. To convert my expenses from Splitwise I used the [script from @ChristopherJohnston](https://github.com/spliit-app/spliit/issues/22#issuecomment-1881632719) as starting point.

Whenever I was entering this group I needed to wait for about 15 seconds until the entries appeared. When it was fully loaded the UI felt a bit sluggish - buttons took some time to respond to clicks.

Therefore I was motivated to implement some sort of incremental expense loading. As it is 2024, I went for a technique called "infinite scroll" over traditional "old-school" pagination. **Infinite Scroll** is a technique that automatically adds the next page as the user scrolls down through content, more content is loaded. User don’t need to wait for pages to preload. So infinite scroll can provide user a better experience.

## Implementation

Changes to component `Page`

  - only load the first 200 expenses (if there are 200 or more)
  - pass preloaded expenses and total expense count to child component `ExpenseList`

Changes to component `ExpenseList`

- Extract `ExpenseCard` (the component that renders an expense list item) from `ExpenseList`
- If there are more expenses to show:
  - append preloading "skeletons" to end of list
  - fetch more expenses when last item in list comes into view (using [`react-intersection-observer`](https://github.com/researchgate/react-intersection-observer))
  - after each fetch increase number of fetched expenses by 1.5 (*)

(*) Database fetch is usually not the issue here, but the length of the list is. The longer the list gets, the longer React needs to redraw. To limit the number of redraws, the next query fetches 1.5 times more items. Therefore, when the list is still short, we add less items (which is fast). The longer the list gets, the more items are added. This is slower, but the list will be completed with less redraws (which is less painful).

## Links

Some resources that helped me implementing infinite scroll

- https://blog.logrocket.com/3-ways-implement-infinite-scroll-react/
- https://medium.com/@ryanmambou/how-to-implement-infinite-scroll-in-nextjs-without-button-99d8ce886985
- https://github.com/researchgate/react-intersection-observer

## Remarks

- dramatic speedup for long lists (startup time is down from 15 to 2 secs)
- for 99% we don't need to load more that the most recent 200 entries
- UI feels a lot more responsive, too
- no "load more" button or "old-school" pagination needed
- works very well with the search button, too

Enjoy! Hope you like it!
Comments and suggestions are always welcome.

### CODE REVIEW

**Comment by ChristopherJohnston** [comment]
This is a great contribution! I also have a split wise-imported expense list (via a script) with similar issues as a result of its size.

nb would also be good to share how you imported - my script is here: https://gist.github.com/ChristopherJohnston/a6e69bd8894f20ecfe127fa4149bd013

**Comment by shynst** [comment]
@scastiel : I think this is a good contribution to spliit. Did you have time to look over it? Looking forward to your input.

**Comment by ChristopherJohnston** [comment]
@scastiel the app is definitely in need of something like this. It is very slow to render the expense list when there is a reasonably large number of expense items (ie 1000+)

**Comment by ChristopherJohnston** [comment]
@shynst are the merge conflicts simple to resolve? This might help things along

**Comment by shynst** [comment]
@ChristopherJohnston should be ready to merge now!

**Comment by ChristopherJohnston** [comment]
Thanks @shynst! @scastiel - when do you think you will be able to catch up on these PRs?

**Comment by scastiel** [comment]
Amazing @shynst!

**Pull request merged**
